name: "Push-to-main"

on:
  pull_request:
    branches:
      - main

jobs:
  pylint_run:
    name: "Run Pylint on the code"
    runs-on: ubuntu-latest
    steps:
    - name: clone repository
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4.6.0
    - name: Install pylint
      run: pip3 install pylint
    - name: Python Linter on dashboard
      run: pylint --fail-under=8 dashboard.py
    - name: Python Linter on pipeline
      run: pylint --fail-under=8 ./pipeline/*.py
    - name: Python Linter on lambda
      run: pylint --fail-under=8 ./lambda/*.py
      
  pytest_run:
    name: "Run Pytest on the code"
    runs-on: ubuntu-latest
    needs: pylint_run
    steps:
    - name: clone repository
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4.6.0
    - name: Install packages
      run: pip3 install -r requirements.txt
    - name: Run pytest on dashboard
      run: pytest dashboard.py
    - name: Run pytest on pipeline folder
      run: pytest ./pipeline/*.py
    - name: Run pytest on lambda folder
      run: pytest ./lambda/*.py
